version: '2'

services:
  app:
    restart: always
    build: ./app
    image: sjbitcode/autoemail-app
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ./env/dev.env
    volumes:
      - ./app:/app
      - ./data:/data
      - ./logs:/app/logs
    command: gunicorn -c /app/app/settings.py run

  nginx:
    restart: always
    build: ./nginx
    image: sjbitcode/autoemail-nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf/nginx.conf
    volumes_from:
      - app
    depends_on:
      - app
